services:
  rust_1.97.1_ssh_container:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - GIT_USER_NAME=${GIT_USER_NAME}
        - GIT_USER_EMAIL=$}{GIT_USER_EMAIL}
    image: ssh-dev-container
    container_name: my_ssh_container
    ports:
      - "2222:22"
    volumes:
      - ${HOST_HOME}/.ssh/id_rsa.pub:/home/dev/.ssh/authorized_keys:ro
      - ../../workspace:/home/dev/workspace
      - ../../dotfiles/.vimrc:/home/dev/.vimrc
    restart: unless-stopped